name: Build

on:
  workflow_dispatch:
    inputs:
      testing_workflow:
        type: boolean
        required: true
        default: false
        description: 'Use dummy kernel config? (for testing workflow)'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: install build deps
      run: |
        sudo apt-get update
        sudo apt-get install pacman-package-manager libarchive-tools libelf-dev
    - name: override test config
      if: ${{ inputs.testing_workflow }}
      run: cp allnoconfig.txt config.x86_64
    - name: fetch sources
      run: |
        gpg --import keys/pgp/*.asc
        ./makepkg_wrapper.sh -o
    - name: build
      run: ./makepkg_wrapper.sh -e -L
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        files: |
          linux-*.pkg.tar.zst
          linux-*.log
        fail_on_unmatched_files: true
